version: "3.18"
services:
  app:
    # env_file:
      # - dev.env
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongodb
    ports:
      - 8000:8000
      - 5173:5173
    volumes:
     - .:/app

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./database/mongodb/db:/data/db
    command: [--auth]
